name: Generate TOC

on:
  push:
    paths:
      - .github/workflows/generate_toc.yml
      - '**/*.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: technote-space/toc-generator@v4
        with:
          COMMIT_MESSAGE: '[actions skip]: TOC'
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
          TARGET_PATHS: README.md,packages/annotation/README.md,packages/codegen/README.md,packages/json_dynamic_widget/README.md,packages/json_dynamic_widget/doc/*.md
