name: Pull Request Checker

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate annotation
        uses: peiffer-innovations/actions-flutter-validate@v2
        with:
          path: annotation
          sarif_file: annotation.sarif

      - name: Validate codegen
        uses: peiffer-innovations/actions-flutter-validate@v2
        with:
          path: codegen
          sarif_file: codegen.sarif

      - name: Validate json_dynamic_widget
        uses: peiffer-innovations/actions-flutter-validate@v2
        with:
          generate_code: true
          path: json_dynamic_widget
          sarif_file: json_dynamic_widget.sarif

