name: Flutter Pull Request Checker

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Run Codegen
        run: |
          flutter packages get
          dart run build_runner build --delete-conflicting-outputs -v
        working-directory: json_dynamic_widget

      - name: Run Codegen Example
        run: |
          flutter packages get
          dart run build_runner build --delete-conflicting-outputs -v
        working-directory: json_dynamic_widget/example

      - name: Validate
        uses: peiffer-innovations/actions-flutter-validate@v1
        with:
          path: annotation

      - name: Validate
        uses: peiffer-innovations/actions-flutter-validate@v1
        with:
          path: codegen

      - name: Validate
        uses: peiffer-innovations/actions-flutter-validate@v1
        with:
          path: json_dynamic_widget
